/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZFooter: typeof import('./src/components/ZFooter.vue')['default']
    ZHeader: typeof import('./src/components/ZHeader.vue')['default']
    ZNavbar: typeof import('./src/components/ZNavbar.vue')['default']
    ZTabbar: typeof import('./src/components/ZTabbar.vue')['default']
    ZTabBar: typeof import('./src/components/ZTabBar.vue')['default']
  }
}
